apiVersion: v1
kind: Service
# metadata:
#   namespace: {{ .Release.Namespace }}
#   name: techtalksapi
#   labels:
#     app: {{ template "techtalksapi.name" . }}
#     chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
#     release: {{ .Release.Name }}
#     heritage: {{ .Release.Service }}
# spec:
#   type: {{ .Values.service.type }}
#   ports:
#     - port: {{ .Values.service.internalPort }}
#       protocol: TCP
#   selector:
#     run: {{ template "techtalksapi.name" . }}
#     release: {{ .Release.Name }}


metadata:
  namespace: {{ .Release.Namespace }}
  name: techtalksapi
spec:
  # type: NodePort
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    run: techtalksapi