apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: db-deployment
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: LoadBalancer


