apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  namespace: {{ .Release.Namespace }}
  name: db-deployment
spec:
  serviceName: db-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: db
    spec:
      terminationGracePeriodSeconds: 10
      
      containers:
      - name: sql2017
        image: microsoft/mssql-server-linux
        imagePullPolicy: Always
        ports:
        - name: dbport
          containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: June@2018
        - name: MSSQL_PID
          value: Developer